INSERT INTO task( `created_at`, `category`, `description`, `title`, `budget`, `latitute`, `longitute`, `date`, `status`, `client`, `executor`, `city` ) VALUES ( STR_TO_DATE('2019-03-09', '%Y-%m-%d'), 3, 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 'enable impactful technologies', 6587, 6.9641667, 158.2083333, STR_TO_DATE('2019-11-15', '%Y-%m-%d'), 1, 15, 18, 457 );
INSERT INTO task( `created_at`, `category`, `description`, `title`, `budget`, `latitute`, `longitute`, `date`, `status`, `client`, `executor`, `city` ) VALUES ( STR_TO_DATE('2019-07-03', '%Y-%m-%d'), 8, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.

Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 'exploit revolutionary portals', 2904, 5.623505, 10.2544044, STR_TO_DATE('2019-12-07', '%Y-%m-%d'), 4, 1, 9, 704 );
INSERT INTO task( `created_at`, `category`, `description`, `title`, `budget`, `latitute`, `longitute`, `date`, `status`, `client`, `executor`, `city` ) VALUES ( STR_TO_DATE('2019-06-27', '%Y-%m-%d'), 5, 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.

Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.

Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 'matrix next-generation e-commerce', 1170, 63.593219, 53.9068532, STR_TO_DATE('2019-11-23', '%Y-%m-%d'), 3, 1, 2, 585 );
INSERT INTO task( `created_at`, `category`, `description`, `title`, `budget`, `latitute`, `longitute`, `date`, `status`, `client`, `executor`, `city` ) VALUES ( STR_TO_DATE('2019-01-01', '%Y-%m-%d'), 5, 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.

Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.

Fusce consequat. Nulla nisl. Nunc nisl.', 'benchmark plug-and-play infomediaries', 838, 20.5800358, -75.2435307, STR_TO_DATE('2019-11-10', '%Y-%m-%d'), 3, 4, 7, 769 );
INSERT INTO task( `created_at`, `category`, `description`, `title`, `budget`, `latitute`, `longitute`, `date`, `status`, `client`, `executor`, `city` ) VALUES ( STR_TO_DATE('2019-09-07', '%Y-%m-%d'), 7, 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 'integrate cross-platform e-business', 7484, 14.9326574, -91.6941845, STR_TO_DATE('2019-12-15', '%Y-%m-%d'), 3, 13, 12, 575 );
INSERT INTO task( `created_at`, `category`, `description`, `title`, `budget`, `latitute`, `longitute`, `date`, `status`, `client`, `executor`, `city` ) VALUES ( STR_TO_DATE('2018-11-01', '%Y-%m-%d'), 6, 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 'enable dot-com niches', 5725, 40.163127, 116.638868, STR_TO_DATE('2019-11-24', '%Y-%m-%d'), 2, 5, 13, 945 );
INSERT INTO task( `created_at`, `category`, `description`, `title`, `budget`, `latitute`, `longitute`, `date`, `status`, `client`, `executor`, `city` ) VALUES ( STR_TO_DATE('2019-09-13', '%Y-%m-%d'), 7, 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 'transform web-enabled relationships', 4414, 44.3794871, 20.2638941, STR_TO_DATE('2019-11-19', '%Y-%m-%d'), 4, 14, 5, 355 );
INSERT INTO task( `created_at`, `category`, `description`, `title`, `budget`, `latitute`, `longitute`, `date`, `status`, `client`, `executor`, `city` ) VALUES ( STR_TO_DATE('2019-04-01', '%Y-%m-%d'), 4, 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.

Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.

Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 'strategize frictionless solutions', 3454, -7.3251485, 108.3607464, STR_TO_DATE('2019-11-14', '%Y-%m-%d'), 1, 3, 12, 260 );
INSERT INTO task( `created_at`, `category`, `description`, `title`, `budget`, `latitute`, `longitute`, `date`, `status`, `client`, `executor`, `city` ) VALUES ( STR_TO_DATE('2019-03-28', '%Y-%m-%d'), 3, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 'innovate seamless metrics', 3101, 43, -87.97, STR_TO_DATE('2019-12-12', '%Y-%m-%d'), 3, 1, 4, 490 );
INSERT INTO task( `created_at`, `category`, `description`, `title`, `budget`, `latitute`, `longitute`, `date`, `status`, `client`, `executor`, `city` ) VALUES ( STR_TO_DATE('2019-05-01', '%Y-%m-%d'), 7, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 'integrate wireless infomediaries', 6562, 41.3410168, -8.3169303, STR_TO_DATE('2019-12-19', '%Y-%m-%d'), 3, 17, 5, 531 );
